package in.co.rays.exception;

public class Exceptiontest {
	public static void main(String[] args) {
		int a =10;
		int b=0;
		String s =null;
		System.out.println(s.length());
		try {
			
		} catch (Exception e) {
			// TODO: handle exception
		}
		
		try {
			int c=a/b;
			System.out.println(c);
		} catch (Exception e) {
			// TODO: handle exception
		}
		
	}

}
